name: GoBuildForCentos
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v .

      # 编译二进制
      # 注意没有使用cgo的务必加上CGO_ENABLED=0，不然可能编译通过但VPS上没有GLIBC或GLIBC版本不一致会导致无法启动
      - name: Build 
        run: CGO_ENABLED=0 go build -o app -tags=jsoniter

      # 将编译出的二进制文件 scp 到你的VPS服务器
      - name: SCP Files 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}  # Secrets中的配置：vps IP地址
          username: ${{ secrets.REMOTE_USER }}  # Secrets中的配置：vps 登录用户名
          port: ${{ secrets.REMOTE_PORT }} # Secrets中的配置：vps 端口
          key: ${{ secrets.SERVER_SSH_KEY }} # Secrets中的配置：vps 上创建的ssh key的私钥内容
          source: 'app,ui,conf'  # 编译出的二进制文件名
          target: ${{ secrets.REMOTE_TARGET }} # Secrets中的配置：scp 到 vps 上的的目录

      # 通过ssh远程执行命令重启vps上的服务
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # Secrets中的配置：vps IP地址
          username: ${{ secrets.REMOTE_USER }} # Secrets中的配置：vps 登录用户名
          port: ${{ secrets.REMOTE_PORT }} # Secrets中的配置：vps 端口
          key: ${{ secrets.SERVER_SSH_KEY }} # Secrets中的配置：vps 上创建的ssh key的私钥内容
          script: ${{ secrets.AFTER_COMMAND }} # Secrets中的配置：scp二进制文件到vps服务器上后需要执行的相关shell命令重启服务